fileprovides: create fileprovides with already present solv files
rpm-software-management/ci-dnf-stack pull request #1346
Opened 2023-07-25 12:59 UTC by kontura

For: https://github.com/rpm-software-management/dnf5/issues/520

2023-07-26 19:57 UTC, evan-goode requested changes

2023-07-26 19:57 UTC, evan-goode commented on dnf-behave-tests/fixtures/specs/fileprovides/agua-1.0-1.fc29.spec
> +planta description
Nit: should be "agua description"

2023-07-27 11:42 UTC, kontura commented on dnf-behave-tests/fixtures/specs/fileprovides/agua-1.0-1.fc29.spec
> +planta description
Fixed. :+1:

2023-07-27 12:25 UTC, evan-goode approved these changes

2023-08-10 12:12 UTC, merged