Enable tests for protected-packages
rpm-software-management/ci-dnf-stack pull request #1431
Opened 2024-01-08 07:18 UTC by j-mracek

Additional changases are related to implementation of support of protected-packages in installroot

Requires: https://github.com/rpm-software-management/dnf5/pull/1110

2024-01-17 21:51 UTC, evan-goode requested changes

2024-01-18 08:18 UTC, j-mracek commented on dnf-behave-tests/dnf/protected-packages.feature
>  # TODO: make protected packages work in installroots first
Sure

2024-01-18 08:24 UTC, j-mracek commented on dnf-behave-tests/dnf/protected-packages.feature
>  # TODO: make protected packages work in installroots first
Fixed

2024-01-18 14:04 UTC, evan-goode approved these changes
Thanks!

2024-01-18 14:05 UTC, merged